ENETMVC/Controllers/EmployeeController.cs
using ENETMVC.Database;
using ENETMVC.Database.Interfaces;
using ENETMVC.Database.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ENETMVC.Models;

namespace ENETMVC.Controllers
{
    [Authorize(Roles = "Accountant")]
    public class EmployeeController : Controller
    {
        private IDatabaseFacadeFactory dbFacadeFactory;
        private ApprovableEmployee employee;


        public EmployeeController() : this(new DatabaseFacadeFactory())
        {
        }

        public EmployeeController(IDatabaseFacadeFactory dbFacadeFactory)
        {
            if (dbFacadeFactory == null)
            {
                throw new ArgumentNullException();
            }
            this.dbFacadeFactory = dbFacadeFactory;
        }

        public ActionResult Index()
        {
            using (var df = dbFacadeFactory.Create())
            {
                var viewModel = new AccountantViewModel()
                {
                    SiteEngineers = df.GetAll<SiteEngineer>(),
                    Managers = df.GetAll<Manager>()
                };
                return View(viewModel);
            }
        }

        private List<SelectListItem> getItems()
        {
            return new ReportController().getItems();

        }

        [Route("Employee/{id:int}/ChangeDistrict")]
        public ActionResult ChangeDistrict(int id)
        {
            ViewBag.District = getItems();
            setEmployee(dbFacadeFactory, id);
            if (getViewModel(employee) != null)
                return View(getViewModel(employee));
            return new HttpNotFoundResult();
        }

        [HttpPost]
        [Route("Employee/{id:int}/ChangeDistrict")]
        public ActionResult ChangeDistrict(int id, District District)
        {
            ViewBag.District = getItems();
            setEmployee(dbFacadeFactory, id);
            employee.District = District;
            update();
            return View(getViewModel(employee));

        }

        private void setEmployee(IDatabaseFacadeFactory dbFacadeFactory, int id)
        {
            using (var databaseFacade = dbFacadeFactory.Create())
            {
                employee = getEmployee(databaseFacade, id);
            }
        }

        private EmployeeViewModel getViewModel(ApprovableEmployee employee)
        {
            if (employee != null)
            {
                var viewModel = new EmployeeViewModel()
                {
                    Employee = employee
                };

                return viewModel;
            }
            return null;
        }

        private void update()
        {
            using (var databaseFacade = dbFacadeFactory.Create())
            {
                try
                {
                    databaseFacade.BeginTransaction();
                    if (employee is Manager)
                    {
                        var manager = (Manager)employee;
                        databaseFacade.SaveOrUpdate(manager);
                    }
                    else
                    {
                        var siteEngineer = (SiteEngineer)employee;
                        databaseFacade.SaveOrUpdate(siteEngineer);
                    }
                    databaseFacade.CommitTransaction();
                }
                catch (Exception)
                {
                    databaseFacade.RollbackTransaction();
                }
            }
        }

        private SiteEngineer getSiteEngineer(IDatabaseFacade databaseFacade, int id)
        {
            return databaseFacade.GetById<SiteEngineer>(id);
        }

        private Manager getManager(IDatabaseFacade databaseFacade, int id)
        {
            return databaseFacade.GetById<Manager>(id);
        }

        private ApprovableEmployee getEmployee(IDatabaseFacade databaseFacade, int id)
        {
            if (getSiteEngineer(databaseFacade, id) != null)
                return getSiteEngineer(databaseFacade, id);
            return getManager(databaseFacade, id);
        }


    }


}

ENETMVC/Controllers/ReportController.cs
using ENETMVC.Database.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using ENETMVC.Models;
namespace ENETMVC.Controllers
{
    [Authorize(Roles = "Accountant")]
    public class ReportController : Controller
    {
        public ActionResult DistrictMonthlyCostReport()
        {
            ViewBag.District = getItems();

            return View();

        }

        [HttpPost]
        public ActionResult DistrictMonthlyCostReport(District District)
        {
            ViewBag.District = getItems();
            ViewBag.messageString = District.ToString();
            String query = "select Name, sum(Costs), sum(Duration) from intervention right outer join Months on Months.id = DATEPart(mm, Created) AND clientId in (select id from Client where District = '" + District.ToString() + "')   AND state = 'COMPLETE' group by Name, Months.Id order by Months.Id;";
            return View(getViewModel(query));
        }

        public ReportViewModel getViewModel(string query)
        {

            var viewModel = new ReportViewModel
            {
                Report = getReport(query),
                GrandReport = getReport("select sum(Intervention.Duration), sum(Intervention.Costs) from Intervention where State = 'COMPLETE'"),

            };
            return viewModel;
        }

        public List<SelectListItem> getItems()
        {
            List<SelectListItem> items = new List<SelectListItem>();

            items.Add(new SelectListItem { Text = District.RURAL_INDONESIA.ToString(), Value = "0" });
            items.Add(new SelectListItem { Text = District.RURAL_NSW.ToString(), Value = "1" });
            items.Add(new SelectListItem { Text = District.RURAL_PNG.ToString(), Value = "2" });
            items.Add(new SelectListItem { Text = District.SYDNEY.ToString(), Value = "3" });
            items.Add(new SelectListItem { Text = District.URBAN_INDONESIA.ToString(), Value = "4" });
            items.Add(new SelectListItem { Text = District.URBAN_PNG.ToString(), Value = "5" });
            return items;

        }

        public ActionResult DistrictCostReport()
        {
            String query = "select District, sum(Intervention.Duration), sum(Intervention.Costs) from Client left outer join Intervention on Client.Id = Intervention.ClientId AND state = 'COMPLETE' group by District";
            return View(getViewModel(query));
        }

        public ActionResult SiteEngineerCostReport()
        {
            String query = "select Employee.Name, sum(Intervention.Duration),sum(Intervention.Costs), avg(Intervention.Duration), avg(Intervention.Costs) from Intervention right outer join  Employee on state = 'COMPLETE' AND Employee.Id = EmployeeId group by Employee.Name order by Employee.Name";
            return View(getViewModel(query));
        }

        public IEnumerable<dynamic> getReport(string s)
        {
            var db = WebMatrix.Data.Database.Open("DefaultConnection");
            return db.Query(s);
        }

        public ActionResult Index()
        {
            return View();
        }

    }
}

ENETMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Intervention Monitoring System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("IMS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("Accountant"))
                    {
                        <li>@Html.ActionLink("Staff", "Index", "Employee")</li>
                        <li>@Html.ActionLink("Reports", "Index", "Report")</li>
                    }
                    @if (User.IsInRole("Manager"))
                    {
                        <li>@Html.ActionLink("Proposed Interventions", "ProposedInterventions", "Intervention")</li>
                        <li>@Html.ActionLink("Past Interventions", "PastInterventions", "Intervention")</li>
                    }
                    @if (User.IsInRole("SiteEngineer"))
                    {
                        <li>@Html.ActionLink("Client", "Client", "Client")</li>
                        <li>@Html.ActionLink("Intervention", "Intervention", "Intervention")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year ENET Care</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>